#!/usr/bin/env node
/* =============================================================================
   build-sitemap.js — regenerates sitemap.xml by walking the repo for HTML.

   Run:  node scripts/build-sitemap.js
   Run it after build-neighborhoods.js, or after adding any page.

   Hand maintained sitemaps drift. This one cannot, because it reads the actual
   files. Priorities are assigned by depth and by a small override table, since
   the home page and the two conversion pages genuinely matter more than an
   individual neighborhood page.
   ========================================================================== */

'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const DOMAIN = 'jenniferbarragan.com';

// Pages that should never appear in search results. brand/ holds the logo
// concept sheet, which is internal working material rather than site content.
// It already carries a noindex, and listing a noindex page in the sitemap sends
// Google two contradictory instructions, so it is excluded here as well.
const EXCLUDE = new Set(['404.html', 'brand/logo-concepts.html']);

// Directory prefixes that never enter the sitemap. g/ holds the noindex
// landing pages the video funnel DMs out; listing a noindex page in the
// sitemap sends Google contradictory instructions, same reasoning as above.
const EXCLUDE_PREFIX = ['g/'];

// Explicit priority and change frequency. Anything not listed falls back to
// the depth based default below.
const OVERRIDES = {
  'index.html':            { priority: '1.0', changefreq: 'weekly' },
  'buyers.html':           { priority: '0.9', changefreq: 'monthly' },
  'sellers.html':          { priority: '0.9', changefreq: 'monthly' },
  'relocate.html':         { priority: '0.9', changefreq: 'monthly' },
  'neighborhoods.html':    { priority: '0.8', changefreq: 'monthly' },
  'accessibility.html':    { priority: '0.3', changefreq: 'yearly' },
};

function walk(dir, out = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('.') || entry.name === 'node_modules') continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) walk(full, out);
    else if (entry.name.endsWith('.html')) out.push(full);
  }
  return out;
}

const files = walk(ROOT)
  .map((f) => path.relative(ROOT, f).replace(/\\/g, '/'))
  .filter((f) => !EXCLUDE.has(f) && !EXCLUDE_PREFIX.some((p) => f.startsWith(p)))
  .sort((a, b) => {
    // index first, then top level pages, then nested
    if (a === 'index.html') return -1;
    if (b === 'index.html') return 1;
    const da = a.split('/').length;
    const db = b.split('/').length;
    return da - db || a.localeCompare(b);
  });

const today = new Date().toISOString().slice(0, 10);

const urls = files.map((f) => {
  const o = OVERRIDES[f] || {
    priority: f.includes('/') ? '0.6' : '0.7',
    changefreq: 'monthly',
  };
  // The home page is served from the bare domain, not /index.html.
  const loc = f === 'index.html' ? `https://${DOMAIN}/` : `https://${DOMAIN}/${f}`;
  return `  <url>
    <loc>${loc}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${o.changefreq}</changefreq>
    <priority>${o.priority}</priority>
  </url>`;
}).join('\n');

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/build-sitemap.js. Do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;

fs.writeFileSync(path.join(ROOT, 'sitemap.xml'), xml, 'utf8');
console.log(`build-sitemap: wrote ${files.length} URLs to sitemap.xml.`);
